service: ride-service4

frameworkVersion: '3'

package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  region: us-east-1
  runtime: nodejs16.x
  memorySize: 512
  timeout: 10 # 10 sec
  logRetentionInDays: 14
  architecture: arm64
  # versionFunctions: false
  stage: dev
  environment:
    SERVICE_NAME: test-test-test

functions:
  getRides:
    handler: index.getMany
    role: lambdaRole2
    events:
      - httpApi:
          path: /
          method: get
  getRide:
    handler: index.getOne
    role: lambdaRole2
    events:
      - httpApi:
          path: /{id}
          method: get
  createOneRide:
    handler: index.createOne
    role: lambdaRole2
    events:
      - httpApi:
          path: /
          method: post
  createManyRides:
    handler: index.createMany
    role: lambdaRole2
    events:
      - httpApi:
          path: /many
          method: post
  updateOneRide:
    handler: index.updateOne
    role: lambdaRole2
    events:
      - httpApi:
          path: /{id}
          method: patch
  updateManyRides:
    handler: index.updateMany
    role: lambdaRole2
    events:
      - httpApi:
          path: /
          method: patch
  deleteOneRide:
    handler: index.deleteOne
    role: lambdaRole2
    events:
      - httpApi:
          path: /{id}
          method: delete

resources:
  Resources:
    lambdaRole2:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: lambdaRole2
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: lambdaPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'dynamodb:*'
                    - 'logs:*'
                  Resource: '*'
    lambdaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: entity
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: entity
            KeyType: RANGE
        TableName: ${self:service}-customerTestTable2
